### ISSUE TITLE
Unsaved changes discard when addin a person

### ISSUE THREAD

**Issue by puggan** [martin-green/skojjt#10]
Reproduce:
1. Star mark the person that was attending
2. Notice someone is missing in the list
3. Search upp and add that person

Expected Result:
The table was extended with one person
and you can continue to mark off the rest of the list

Current result:
The table was extended with one person
and all marks get unchecked, so you need to start over.

Alternative expected result.
Dialog like 'You have unsaved changes, save them before continue?'

**Comment by martin-green** [comment]
Japp, det bör fixas.


Den 2016-11-09 kl. 14:05, skrev puggan:
