### ISSUE TITLE
Möjligt skapa dublettmöte - närvaron försvinner

### ISSUE THREAD

**Issue by buzzzy** [martin-green/skojjt#22]
Anta att man skapat ett möte och fört in närvaro. Om man sedan av misstag skapar ett nytt möte den dagen (kollade inte om det går att skapa med annan tid), då skriver det över närvarodatan dvs. man förlorar närvaroregistreringen.

**Comment by martin-green** [comment]
Fixade så att den uppdaterar existerande möte.
OBS: man kan bara ha ett möte per dag, det är vad man kan få bidrag för.

**Comment by puggan** [comment]
"man kan bara ha ett möte per dag"
Vi har en avdelning som har 2 möten per dag, hälften av barnen är närvarande 18-19, och resten är närvarande 19-20.

Kommer det bli problem om de rapporterar in dem som 2 olika möten?
![screenshot_20170127_081513](https://cloud.githubusercontent.com/assets/866668/22363187/c43f70ec-e468-11e6-9812-2b33c6ee8921.png)

**Comment by martin-green** [comment]
Nyckeln för möten hade tiden med. Så man kunde ha flera möten per dag, med olika tider.
Jag ändrar id genereringen men gör ingen konvertering nu. Så om man skapar ny på en tidigare mötesdag så kommer man få en dubblett.
