### ISSUE TITLE
Pågående registrering töms om man lägger till ny person

### ISSUE THREAD

**Issue by buzzzy** [martin-green/skojjt#29]
Upptäckte just att pågående registrering töms om man lägger till ny person. Kanske man kan varna för detta?

**Comment by martin-green** [comment]
Den varnar att du försöker lämna sidan med osparade ändringar. Det funkar i FF, Chrome, Android.

**Comment by buzzzy** [comment]
Skumt, jag är 100 på att den inte varnade, men jag lämnade inte sidan, jag var kvar på samma sida, hade reggat några närvarorutor, lade till en scout, sedan var det blankt på det mötet. Men OK! Chrome på Win10.

**Comment by buzzzy** [comment]
Jag mailar en film som visar problemet.
