### ISSUE TITLE
0 i alla fält för föreningsredovisningen

### ISSUE THREAD

**Issue by benganellison** [martin-green/skojjt#32]
Verkar vara något fel i föreningsredovisningen får bara 0 i alla fälten för Hjällbo

**Comment by benganellison** [comment]
![screenshot_20170617-211014](https://user-images.githubusercontent.com/23585524/27255614-ce35db42-53a1-11e7-8015-aa4185053f57.jpg)

**Comment by martin-green** [comment]
Ja det beror på en bugfixen för #31 . Den lägger till ett årtal på varje person.
Kan du tänka dig att köra importen igen så fixar det sig. 
(Hur gjorde du den långa bilden?)

**Comment by benganellison** [comment]
Samsung har en sådan funktion inbyggt när man gör skärmdumpar.

Löste sig med en import

**Comment by benganellison** [comment]
![screenshot_20170618-141408](https://user-images.githubusercontent.com/23585524/27260599-80474990-5430-11e7-86a8-be1e3ff2cb51.png)
