### ISSUE TITLE
Skapa sensus närvarolista

### ISSUE THREAD

**Issue by martin-green** [martin-green/skojjt#34]
Man vill kunna generera en närvarolista för Sensus från en pdf mall (se bifogad). Mallen kan behöva expanderas med fler möten (30 st). En lösning är att göra en html mall som ser ut som formuläret och sen generera pdf med xhtml2pdf och Jinja: [Exempel](http://flask.pocoo.org/snippets/68/)
Man behöver kunna dela in avdelningen i flera grupper så att man kan få bidrag för varje grupp separat. Varje grupp behöver minst en ledare, och minst två deltagare.
[sensus_template.pdf](https://github.com/martin-green/skojjt/files/1226488/sensus_template.pdf)
Rapporten kan sedan laddas hem som en ifylld pdf, skrivas ut, signeras, och skickas till Sensus.

(Om Sensus hade haft ett vettigt API hade vi kunnat använda det.)

**Comment by stefer** [comment]
När vi i Lerums scoutkår talat med sensus så sade de att man skulle kunna använda patrullerna som indelning i grupper.
Patruller finns i scoutnet, så man skulle kunna utöka modellen i skojjt för att importera det också.
Jag vet att det finns lite administrativa problem med grupperna, tex att det måste finnas en ledare per grupp, vilket inte mappar så bra mot patrullerna, eftersom det ofta är färre ledare än patruller.

**Comment by martin-green** [comment]
Skojjt skapar en lista per patrull. Man kan ändra patrull i skojjt.
