### ISSUE TITLE
Frånvaro <<|>> Närvaro-toggle-knapp

### ISSUE THREAD

**Issue by rkalitta** [martin-green/skojjt#37]
Oftast så är det lättare att säga vilka som inte är närvarande, dvs frånvarande. Det är lite mödosamt ibland att behöva markera alla som är där. Istället vore det smidigare om man kunde (invertera frågan och) markera endast de som är frånvarande. Alltså istället för att markera 30 st närvarande, klicka på en liten knapp längst upp i listan som gör närvarolistan till frånvarolista, och nu markera endast 2 frånvarande. 

Det enda som är skillnaden mellan lägena är hur datat presenteras i UI. Man kan när som helst klicka på knappen för att växla mellan lägena.

**Comment by puggan** [comment]
Rent tekniskt skulle jag nog föredra att det implementerads med hjälp av en "markera alla"-knapp.

dvs är nästan alla närvarande, klicka på markera alla, och sen klicka på de 2 som inte ska vara markerade, på så sätt är listan fortfarande en närvaro-lista, men det går ändå fort att markera 28 av 30.

**Comment by martin-green** [comment]
Ja, markera alla eller en invertera knapp skulle funka. Det är en lätt sak att implementera, lite script i troop.html. @rkalitta, @puggan: kan jag se fram emot ett pull-request?

**Comment by puggan** [comment]
Lite många bollar i luften för tillfället, så blir ingen PR de kommande veckorna.

**Comment by stefer** [comment]
Jag håller på med denna. Kan inte assigna mig på den, för jag är inte contributor.

**Comment by stefer** [comment]
Kan någon titta på min PR #45?
