### ISSUE TITLE
Läsa in från Scoutnet

### ISSUE THREAD

**Issue by MagnusCalen** [martin-green/skojjt#39]
Det vore önskvärt att alla ledare (eller användare) kan läsa in uppgifter från Scoutnet till Skojjt. I dagsläget är denna funktion lagd som en administratörsfunktion.

**Comment by martin-green** [comment]
Jag vill ha koll på vem som kan göra importerna från scoutnet och jag försöker minska antalet skrivningar i database pga ett begränsat antal i GAE. Jag kan dela ut kåradmin till dig.

**Comment by MagnusCalen** [comment]
![onskad funktion for den som registrerar narvaro](https://user-images.githubusercontent.com/34924529/34442486-c4ef7510-ecc2-11e7-8751-6b2eaaa0efd9.png)

Jag kan bara insistera på att användarvänligheten vore så mycket böttre om de som registrerar närvaron också kan uppdatera med aktuella uppgifter från sin kårs scoutnetregister. När vi är många ledare i kåren som löpande uppdaterar medlemsregistret käns det naturligt att också ku´nna ladda hem ett aktuellt medlemsregister till Skojjt utan att för den delen vara administratör. 

Ber om att få en knapp som heter 'Importera medlemsregister' eller vad den nu kan heta. Användaren/ledaren som gör detta ska ej ange några APIer eller annat. Att fylla i sådana upgifter, det är admionistratörsjobb.

Mvh
/MC
