### ISSUE TITLE
Sensus rapporten ser inte bra ut i alla webläsare

### ISSUE THREAD

**Issue by martin-green** [martin-green/skojjt#41]
Sensus listorna funkar bäst i chrome. Men med Firefox så går den sönder vid utskrift. I Internet Explorer 11 är den helt trasig. Jag har inte provat safari på mac, eller iphone.
@benganellison; är det något du kan titta på?

**Comment by benganellison** [comment]
Jag ligger utslagen i hög feber, men det är klart jag kan titta på detta när jag frisknat till. Borde inte vara en så svår grej

**Comment by benganellison** [comment]
Kan jag få en skärmdump så jag kan börja tänka på det utan dator?

**Comment by MagnusCalen** [comment]
Fungerar bra i Safari på iPhone. Fungerar inte bra i vaeken Edge elelr INternet Explorer på dator, Win10.

**Comment by MagnusCalen** [comment]
[Sensus_i_IE.pdf](https://github.com/martin-green/skojjt/files/1593545/Sensus_i_IE.pdf)

**Comment by MagnusCalen** [comment]
[Sensus_i_Edge.pdf](https://github.com/martin-green/skojjt/files/1593585/Sensus_i_Edge.pdf)

**Comment by stefer** [comment]
Så här ser det ut i Edge. Det är flex-layouten som krånglar. Jag kan lägga lite tid på att se om man kan lägga till något i stylingen som gör att det fungerar i Edge.

![image](https://user-images.githubusercontent.com/1500560/34444313-8cb92dac-eccd-11e7-8a4a-df83ab0b020d.png)

**Comment by martin-green** [comment]
Vore toppen om du kunde kolla på det. Här är mallfilen:
https://github.com/martin-green/skojjt/blob/master/templates/sensusnarvaro.html

**Comment by stefer** [comment]
Nepp, jag kan flex-layout för dåligt. :-(
Det verkar som att flex i en tabell funkar dåligt i Edge. flex-support i IE 10 och 11 är tydligen väldigt buggig.
Varför har man display: flex i varje rad i tabellen?

Det enda jag hittat var att du varit lite inkonsekvent med klasserna i de första tre kolumnerna i de första tre raderna i tabellen. PersonalId och sex saknades i några. Men det gör inte någon skillnad.

**Comment by benganellison** [comment]
flex var det enda som jag lyckades använda för att få till lika breda kolumner

**Comment by benganellison** [comment]
@martin-green  ser att du ändrat alla ID till classer så det tar lite längre tid för mig att merga mina ändringar men håller på

**Comment by martin-green** [comment]
Tack @benganellison, nu det ser bra ut i Edge!
Men IE11 är bara lite bättre. Den verkar inte hantera flex så bra. Kanske inte värt besväret att försöka fixa det.

**Comment by benganellison** [comment]
Kan du se hur stor andel som använder IE?

**Comment by stefer** [comment]
Jag kan inte köra igång lokal debugging, men har pillat med stylingen i en lokal fil.
Har förenklat layouten i tabellen och får det att aligna riktigt snyggt.
Men, de rundade hörnen försvann i Chrome.
[Sensus Närvarolista_kort_new.zip](https://github.com/martin-green/skojjt/files/1594555/Sensus.Narvarolista_kort_new.zip)

![image](https://user-images.githubusercontent.com/1500560/34455850-13396b5c-ed88-11e7-9e98-9c144d33b062.png)

Nu kallar familjen igen...

**Comment by stefer** [comment]
Japp, där kom det en PR. 
Jag har testat styling med den attachade filen.
Templaten är ändrad enligt samma mönster, men ej testad med data.

[Sensus Närvarolista_kort_new.zip](https://github.com/martin-green/skojjt/files/1594808/Sensus.Narvarolista_kort_new.zip)

**Comment by benganellison** [comment]
Behövdes inte de övriga tre fälten som finns i pdfen? De var en av orsakerna som jag gjorde layouten så som jag gjorde
![screenshot_20171231-201249](https://user-images.githubusercontent.com/23585524/34463806-fb6a6cf2-ee67-11e7-8c07-a9ce8b4a872d.png)

![screenshot_20171231-201650](https://user-images.githubusercontent.com/23585524/34463809-0bc2dbac-ee68-11e7-825b-790fb2099e71.jpg)

**Comment by stefer** [comment]
@benganellison Jag såg inte Kvinna/ej godkänd/återanmälan i chrome, så jag antog att det var fält som inte användes. @martin-green Var det fält som skulle användas? De populerades inte i python-koden.

Underskrift av ansvarig på finns kvar, det var bara det att det inte var med i min minimala html som jag använde för att fixa css:en.
