### ISSUE TITLE
Rensa gammalt data

### ISSUE THREAD

**Issue by stefer** [martin-green/skojjt#42]
En funktion för att kunna rensa bort gamla terminers data för en kår.
Användare som inte längre finns i scoutnet plockas bort på samma gång.

Kåren har frågat om hur man plockar bort de som inte är medlemmar längre,
men som jag ser det måste de finnas kvar så länge det finns data kopplat till dem.

Ett alternativ är att man anonymiserar dem när de inte längre finns i scoutnet, 
så att man tex behåller scoutnets id, men nollställer alla andra fält.

**Comment by martin-green** [comment]
Det finns en "removed" flagga på alla personer som ska användas till det här. Jag har bara inte gjort någon funktion för att sätta den på personregistersidan. Det bästa vore om importen kunde sätta den, dvs se vilka personer som inte finns med vid import.

**Comment by stefer** [comment]
Vad är det som återstår på denna? Kan jag hjälpa till?
