### ISSUE TITLE
Sensus timmar per möte

### ISSUE THREAD

**Issue by martin-green** [martin-green/skojjt#46]
I sensuslistan ska summeringen av timmar bara vara pet möte inte multiplicerat med antalet närvarande.

**Comment by stefer** [comment]
Jag tar denna

**Comment by stefer** [comment]
#47 Borde fixa detta, om jag förstått uppdraget rätt.
1,5 timmas möte blir 2 lektionstimmar.

**Comment by martin-green** [comment]
fixed with https://github.com/martin-green/skojjt/commit/223475d1f35890da59a2145997f6fa929ecf70ca
