### ISSUE TITLE
Kön från Scoutnet

### ISSUE THREAD

**Issue by sakjur** [martin-green/skojjt#50]
Kul att någon äntligen jobbar på att göra vettig närvarorapportering för scouter 😄 

I kommentaren i `scoutnet.py:39` så anges `Annat` ange icke-person och gör att deltagaren inte kan tolkas korrekt. `Annat` kan anges i Scoutnet av en deltagare som kön, och innebär inte nödvändigtvis att det inte handlar om en fysisk person.

https://github.com/martin-green/skojjt/blob/637e06a4b8ae4a0a2ba4d9c328d21b21bb6eaa8c/scoutnet.py#L37-L40

**Comment by stefer** [comment]
Man kan fråga sig varför "hittepå-kontona" skall exponeras i API:et överhuvudtaget. Finns det någon vettig anledning till det? Kan scoutnet filtrera bort dem istället för att sätta en konstig status?

När vi fixat detta så borde vi kanske lägga till stöd i Skojjt för könet "Annat", eftersom det är ett giltigt värde.

**Comment by mrManner** [comment]
Jag tror inte Scoutnet har stöd för att filtrera bort kontona ur API:et idag, men jag ska kolla upp om vi kan få in ett sådant filter. Med risken att någon använder sina hittepåkonton även via API, folk är påhittigare än man tror ibland :-/

Skulle en hittepå-konto-status som enkelt kan filtreras bort av konsumenten vara ett bra substitut?
