### ISSUE TITLE
Skicka email med info när man lägger till person i skojjt

### ISSUE THREAD

**Issue by martin-green** [martin-green/skojjt#52]
Om man lägger till någon i skojjt så hamnar dom i "medlemmar som inte godkänts" i scoutnet.
Det är viktigt att man går in i scoutnet och godkänner, sätter avgift, avdelning och patrull.
Skojjt borde skicka det i ett email till den som lägger till en person.

**Comment by mrManner** [comment]
FYI: Jag har beställt en liknande funktion i Scoutnet, så att medlemsregistrerare alltid får en notifikation när någon registrerar sig på kårens kölista. I dagsläget skickas bara notifikationer när Scoutnets inbyggda registreringsformulär används, men det rimliga är att API;et behandlas lika.

Om Scoutnet hinner före lär ni alltså inte behöva implementera det här :)

**Comment by martin-green** [comment]
@mrManner: Intressant, hur gör du såna request?
Kan vi lägga till så att man kan sätta rätt avdelning, patrull och avgift direkt i API:et också?

**Comment by mrManner** [comment]
@martin-green Jag har förmånen att jobba med IT-frågor och lite utveckling på Scouterna, bland annat beställning av Scoutnet :) 

Jag ska kika på vad som är möjligt — att få till ett mer heltäckande och ”normalt” API är någonstans på sjätte eller sjunde plats på priolistan just nu, men vi betar av den hyfsat snabbt. Vet att det finns efterfrågan på att kunna göra samma sak i det inbyggda registreringsformuläret i Scoutnet, så det finns hopp.
