### ISSUE TITLE
Problem att importera personer utan personnummer

### ISSUE THREAD

**Issue by flindeberg** [martin-green/skojjt#57]
Misstänker att nedan ställer till det för personer utan personnummer. Har inte testkört ändringar ännu. Det är alltså möjligt för det äldre gardet att vara reggade i scoutnet utan personnummer, föreslår att importen helt enkelt hoppar över dessa.

```
## dataimport.py / 151-153
if person == None:
  id = p["personnr"].replace('-', '')
  person = Person.get_by_id(id, use_memcache=True) # attempt to find using personnr, created as a local person
```

Det faktiska felmeddelandet:

> Importfel: Key path element must not be incomplete: [Person: ]

**Comment by martin-green** [comment]
Fixat. Nu visas en varning i importloggen i stället. Såna fel ska fixas i scoutnet.
