### ISSUE TITLE
Önskemål om att på personsidan visa uppgifter till anhörig1 & 2

### ISSUE THREAD

**Issue by Armandur** [martin-green/skojjt#63]
Det vore önskvärt att kunna visa anhörig1 och 2:s namn och kontaktuppgifter på personsidorna (när man trycker på ett namn i närvarolistan).

Den e-post som registreras i scoutnet i e-postfältet (primär e-postadress) är ju den som är tänkt att vara personlig till scouten, från början oftast en av föräldrarna, när de sedan blir äldre byts den ofta till en personlig, framförallt för att de ska kunna logga in i scoutnet själva (det uppstår också problem här om en förälder blir scoutledare och barnen till denne har förälderns e-postadress som primär e-postadress), men vi vill ju oftast ha kvar kontaktuppgifterna till vårdnadshavarna, i alla fall tills de fyllt 18 år.

**Comment by stefer** [comment]
Man får tänka sig för så att man inte sparar för mycket om personen i skojjt. GDPR lär ju  gälla för föreningar också, och då måste vi kunna motivera lagringen och hantera det på rätt sätt.

Jag tycker att vi skall hålla minimalt med data om personer i skojjts databas.

**Comment by Armandur** [comment]
Jag håller med, som närvaroregistreringsverktyg är uppgifterna om scouten helt tillräckliga. Det går ju iofs att lösa om man meddelar att man överför personuppgifterna till Skojjt och i vilket syfte (i det här fallet att ha tillgång till kontaktuppgifter till vårdnadshavare), men det är kanske är lite åt feature-creep hållet som sagt.

På lång sikt vill jag se en implementation/frontend för scoutnet som är lika lätt att använda som skojjt och med integrerade närvaroregistreringsfunktioner, men det går ju inte så fort på den fronten.

**Comment by stefer** [comment]
Det borde vara ok att visa denna information så länge man inte sparar den i skojjt. Man skulle alltså kunna ha en funktion som visar mer detaljer om en person där det hämtas direkt från scoutnet.
Så, man kan söka smidigt i skojjt, hitta en person, men när man skall visa detaljer så hämtar man det on demand.

**Comment by rkalitta** [comment]
@stefer Naturligtvis ska vi inte spara mer data än nödvändigt i Skojjt. Men. Det är vid det dagliga användandet av Skojjt som namn, mobil, e-post till medlem samt namn mobil, e-post för anhörig 1 och 2 är uppgifter som vi (i allafall jag) har mest behov av i verksamheten. Oftast för att enkelt kolla om man är försenad/sjuk, eller för att snabbt kunna meddela anhörig om något har hänt. Och att då kunna använda Skojjt som ett verktyg för att ge ansvariga, funktionärer och andra som måste ta ansvar för scouterna möjlighet att på ett enkelt sätt få tillgång till nödvändiga kontaktuppgifter, är en stor fördel. Och kan då också på ett enkelt sätt få bort diverse hemmagjorda utskrivna listor, öka säkerheten och göra det enklare för en scoutkår att följa GDPR. 

GDPR handlar inte bara om en massa "vi får inte". Utan mera om hur vi gör det. Scoutkåren kan enkelt motivera behovet att ha tillgång till kontaktuppgifter till anhöriga i sina mobiler. Uppgifter som inte lagras på ett papper eller i ledarens privata mobil, utan i en app som hämtar data från Scoutnet. Om datat sedan sparas i Skojjt eller inte är mer en fråga om tillgänglighet. För min del skulle jag t o m helst kunna köra Skojjt helt off-line. Dvs ha all info lokalt i mobilen. Det är inte allt för sällan man inte har täckning på mobilen. Men det är en annan fråga som sagt.

**Comment by tobbee** [comment]
Jag vill också ha tillgång till anhörig 1 och anhörig 2 så jag har ändrat koden för att få till det. Det kommer snart en PR på detta. Ur GDPR-synpunkt skulle jag vilja att man slutar lagra personnummer. I Stockholm behövs inte det för ansökan av bidrag utan födelsedatum + postnummer räcker. Även på andra orter skulle man kunna tänka sig att inte lagra personnumret i "skojjt" utan hämta det från Scoutnet när man vill göra en rapport. Medlemsnumret räcker som unik identifikation. Återkommer nog med kod här också.

**Comment by Armandur** [comment]
Ja, jag är benägen att hålla med, även fast min kommentar ovan. Jag jobbar
ju administrativt inom Svenska kyrkan och hanterar en hel del
personuppgifter där.

Bara vi berättar att vi hanterar uppgifter om anhöriga och kan styrka
varför vi gör det, så bör (observera bör, inte ska :)) det inte vara några
problem.

Visst man kan logga in i Scoutnet och hämta uppgifterna där också, men
väger man in den tid som uppgifterna behöver fås in på i ett sådant läge
att det behövs för då det skett en skada eller annan allvarlig händelse
etc., då kan man motivera det med att det tar för lång tid att hämta det
från Scoutnet (som det ser ut just nu). Alternativen till att ha det i
skojjt är ju just scoutnet (för långsamt), papper (osäkrare lagring och
inte tillgängligt för alla ledare samtidigt, alternativt personuppgifter på
flera ställen, fler papper) eller att man har det i något annat delat
dokument/tjänst/Messenger.

Är ni med på mitt resonemang?

Den mån 11 feb. 2019 20:05Torbjörn Einarson <notifications@github.com>
skrev:

**Comment by tobbee** [comment]
Nu finns PR #75 med koden för att få ut detta. 
Vi har hälsokort för känsliga uppgifter men telefonnummer, email och födelsedatum borde vi kunna motivera att ha lätt tillgängligt i ledarnas telefoner.

**Comment by kallemooo** [comment]
Hej

Efter att ha följt eran diskussion ett tag så har jag följande kommentarer. (som blev ganska långa)

**Roller i scoutnet**
Scoutnet använder roller för att definiera vad man kan se på andre medlemmar i kåren.
t.ex kan en ledare bara få ut information om scouterna i sin/sina avdelningar.
Används informationen ifrån scoutnet bör man följa den här indelningen.

**Personnummer**
Personnummer är enligt GDPR en så kallad "extra skyddsvärd" personuppgift. Det innebär att man ska ha väl motiverade skäl till att använda personnummer.
Att ta med personnummer ifrån scoutnet för att kunna hantera krav ifrån kommunerna är troligtvis ok för de föreningar vars kommun kräver det.
I alla andra fall är det troligtvis inte ok och medlemsnumret ska användas som unik identifierare.

Dock bör bara föreningsadministratören kunna se personnummer. I scoutnet är det ytterst få roller som kan se hela personnumret. (ordförande, medlemsregistrerare bland annat)
Om det går att ordna så att man bara hämtar personnummer när exporter till kommuner skapas så löser man troligtvis de hör problemen.


Att ledare enkelt ska kunna se telefonnummer, email och födelsedatum för sina scouter borde vara enkelt att motivera. 

Hälsningar 
Karl Thorén
Landvetter scoutkår

**Comment by tobbee** [comment]
Nu är anhöriga medtagna i deltagarsidan. Vi skulle kunna försöka få till ett filter så ledare är begränsade till sina egna avdelningar. 

Håller med om att personnumret bör tas bort så långt som möjligt. Det används dock fortfarande som personindex i skojjt, så jag tänkte skriva lite kod för att byta ut det mot medlemsnumret i Scoutnet istället.

Denna diskussion om anhöriga borde vi dock kunna stänga.

**Comment by martin-green** [comment]
Jag hade medlemsnummer som id i skojjt först. Det var när jag gjorde så 
att man kan lägga till nya personer från skojjt till scoutnet (kölistan) 
som jag behövde ett unikt id som skojjt och scoutnet har gemensamt, 
personnr.

Jag har skickat en begäran till scoutnet att kölist-api ska returnera 
det medlems id som det blev när man lägger till.

Men det finns andra saker som behöver personnummer, sensus, man/kvinna, dak.

Den 2019-02-12 kl. 20:34, skrev Torbjörn Einarson:

**Comment by tobbee** [comment]
Jo, personnumret kan behövas i vissa rapporter, men det är ju rätt sällan så då borde man kunna hämta det när man vill generera dessa rapporter. 

Även att generera man/kvinna från personnumret men det kan vi ju göra utan att lagra det.

Återstår nya medlemmar som temporärt skulle kunna ha personnummer som medlemsnummer och sen byta. 

Får du till din ändring mot Scoutnet slipper man dock den sista komplikationen och det är värt en del.
