### ISSUE TITLE
Medlem importeras inte in från Scoutnet

### ISSUE THREAD

**Issue by rkalitta** [martin-green/skojjt#65]
Hur jag än försöker justera medlemsuppgifter i Scoutnet för att Skojjt ska "reagera" så "ser" importen inte scouten. Tips på vad jag kan göra, förutom att registrera scouten manuellt i Skojjt? Alltså funktionen lägga till person hittar alla i kåren utom denna scout. Och om jag registrerar en person i Skojjt, som redan finns i Scoutnet, vilka aber kan jag springa på då? Vad behöver ni av mig för att kunna göra en felsökning?

**Comment by martin-green** [comment]
Vi tar det här offline!

**Comment by rkalitta** [comment]
Gärna!

Vad har du för nr? Sitter i telefonmöte just nu. Men kan ringa om en stund.
Ok?

Hälsningar
Robert Kalitta



Den tors 18 okt. 2018 kl 20:50 skrev Martin Green <notifications@github.com
