### ISSUE TITLE
Fel format på Excel-fil vid export

### ISSUE THREAD

**Issue by rkalitta** [martin-green/skojjt#66]
När filen öppnas i Excel klagar Excel på att filformatet och filtillägget inte stämmer överens. 
![image](https://user-images.githubusercontent.com/32906424/47723252-68e4f880-dc54-11e8-8123-9f3f982de9f8.png)

När man sedan öppnat filen har Excel inte tolkat å ä ö i cellerna på rätt sätt. Ö blir Ã–, ä blir Ã¤, t ex. 

Inte UTF-8?

**Comment by martin-green** [comment]
@puggan kan vi ta bort excel alternativet? Jag kan inte få det att funka, och så har vi en xlsx export nu.
csv verkar ok.

**Comment by puggan** [comment]
xls-alertnatviet var ju främst till för att lösa MS Excels problem med csv-filer, nu när de har en egen export (har dock inte testat den), så räcker csv-filen för övriga spredsheets program.

**Comment by puggan** [comment]
https://github.com/martin-green/skojjt/commit/93868258154a46abb4e4c77e959151ed1fc2dfc6

**Comment by rkalitta** [comment]
Wow! "Excelrapport" har jag inte sett. Den är ju nästan likadan som den rapport jag måste posta fysiskt till kommunen. Det har varit en del strul med "Exportera XLS" för att få till rapporten. Så för min del kan vi ta bort "Exportera XLS". Får ju ändra på mina rutiner och mallar för att anpassa mig mot "Excelrapport", men så är livet.

Och jag ser ju genast att jag ska göra en ny förfrågan på förbättring av "Excelrapport" .... i en egen tråd.
