### ISSUE TITLE
Förslag på Excel export

### ISSUE THREAD

**Issue by rkalitta** [martin-green/skojjt#67]
Vore kanon om Excel-filen som genereras vid export kunde innehålla lite mer info och var i det nya XML-formatet. Bifogar ett exempel. Veckonummer måste räknas ut, annars finns all info redan i Skojjt. De färgade kolumnerna till höger ska innehålla formlerna, så kan man enkelt redigera manuellt i Excel-filen i efterhand om det behövs och få rätt värden i cellerna direkt. Tänker att dokumentet får bli dynamiskt i antal kolumner efter antal träffar under en termin. Men även dynamiskt i antal rader efter antal medlemmar i avdelningen.

Excel-exporten är annars min räddning, eftersom vår kommun envisas med att vi måste redovisa på papper. Endast föreningar under RF får redovisa digitalt.
[Exempel Närvaro Utmanare 2018 VT.xlsx](https://github.com/martin-green/skojjt/files/2544483/Exempel.Narvaro.Utmanare.2018.VT.xlsx)

**Comment by puggan** [comment]
Så som exporten fungerar idag, är att den tar det som finns på skärmen, och gör anitingen en vanlig csv fil, eller en tab-separerad csv med filendelsen ".xls".

```
function(click_event) {
  return csv_link.href = csv2href(data2csv(table2data(document.getElementById("maintable")), ";"));
}
```

Så att göra ändringar i den exporten är nog svårt.

Ser 2 lösningar:
* antingen koda en helt separat export
* göra en ny flik i din excel mall, och klistra in datan från skojt i flik 2, och låta formler i flik 1 hämta rätt information.

**Comment by rkalitta** [comment]
Aha. Ja det var ju en snitsig liten genväg. Nedre andra alternativet är ju lite så jag måste göra idag. Fast jag skalade bort en del i exempelfilen för att hålla det lite generellt i mitt förslag.

Min tanke från början var att läsa in xml-filen och sedan generera en Excel-fil med rätt data på rätt plats. Har dock inte haft möjlighet bygga lösningen ännu. Ville kolla med er om ni har något på G, om det är värt att lägga tid på det. Excelfilen hade kunnat vara en kompromis.

Hälsningar
Robert Kalitta

Från: puggan
Skickat: den 3 november 2018 12:11
Till: martin-green/skojjt
Kopia: rkalitta; Author
Ämne: Re: [martin-green/skojjt] Förslag på Excel export (#67)

Så som exporten fungerar idag, är att den tar det som finns på skärmen, och gör anitingen en vanlig csv fil, eller en tab-separerad csv med filendelsen ".xls".
function(click_event) {
  return csv_link.href = csv2href(data2csv(table2data(document.getElementById("maintable")), ";"));
}
Så att göra ändringar i den exporten är nog svårt.
Ser 2 lösningar:
• antingen koda en helt separat export
• göra en ny flik i din excel mall, och klistra in datan från skojt i flik 2, och låta formler i flik 1 hämta rätt information.

**Comment by puggan** [comment]
Testa att klistra in din närvaro export i flik 2.
(Har inte ms Office, så blev en ods-fil)

[Narvaro_mall.zip](https://github.com/martin-green/skojjt/files/2544930/Narvaro_mall.zip)

**Comment by rkalitta** [comment]
Jo, det funkar ju. Gör på liknande sätt idag. Får duga tills vidare.

Trist bara formateringen inte funkar. Namnen i exportfilen blir såhär:
Jesper Ã–stborg
Ole RÃ¶nning Kristiansson
Agnes AndrÃ©n
Erik HÃ¤gred
Frida RosÃ©n Sandberg

Excel verkar inte veta hur den ska tolka teckenuppsättningen. Tittar jag i
filen så är å ä ö rätt. Men när jag öppnar filen i Excel blir det fel. Vet
inte hur jag ska lösa det. Tips?

Hälsningar
Robert Kalitta



Den lör 3 nov. 2018 kl 13:02 skrev puggan <notifications@github.com>:

**Comment by puggan** [comment]
Så Excel förväntar sig att filen ska vara i Latin-1 encoding, men webläsaren ger dig filen i UTF-8 encoding.

Funkar fint med libreoffice + firefox + ubuntu. Men är antagligen för att Libreoffice är smatare.

Excel kanske gör rätt om man börjar filen med en BOM-markör, ska exprimentera lite när jag har tillgång till en dator med Excel.

ref: https://sv.wikipedia.org/wiki/Byte_order_mark

**Comment by puggan** [comment]
Excel 2007 och nyare har stöd för BOM, så ser om jag kan lägga in det.

ref: https://stackoverflow.com/a/155176/885872
