### ISSUE TITLE
Klickbara personuppgifter

### ISSUE THREAD

**Issue by rkalitta** [martin-green/skojjt#69]
Saknar möjligheten att kunna klicka och använda mejladressen och telefonnummer i personregister, både i söklista och personprofilen. Föreslår att lägga till mailto: och tel: länkar på dessa uppgifter så att man kan klicka på dem för att kunna mejla eller ringa dem direkt från listan eller personprofilen. (Ser för övrigt inte syftet med att personuppgifterna i personprofilen ligger i textfält, de går ju inte att redigera).

**Comment by puggan** [comment]
De personer som är syncade från scoutnet går nog inte rediger, medans de personer som är tillagda i skojjt, går att redigera. Därav tror jag att der är input fält.

**Comment by rkalitta** [comment]
Aha. För att göra det enkelt så är inget klickbart i personprofilen då. Telefonnummer och mejl i söklistan görs klickbara. Samt för att göra det överskådligt tas personnummer och adress bort ur söklistan. En idé för att göra det ännu enklare är att låta endast kåradmin komma åt personprofil (skapa och se alla personuppgifter som finns i Skojjt). Medans vanlig användare endast ser och kommer åt söklistan.
