### ISSUE TITLE
Ta bort Personnummer

### ISSUE THREAD

**Issue by rkalitta** [martin-green/skojjt#70]
Ser inte behovet av att personnummer finns med som uppgift i personregister. Samtidigt lite känsligt för en del, och GDPR gör det inte lättare. Byt ut uppgiften mot avdelning (enl. Scoutnet) istället. Och kanske t o m lägga till patrull när man ändå håller på. 

Alternativt att det endast är kåradmin som ser detta. Vanliga användare ser inte personnummer.

**Comment by puggan** [comment]
Kräver inte komunen att personnummeret är med i exporten?
Om det krävs i exporten, så måste den lagras, annars funkar inte exporten.

**Comment by rkalitta** [comment]
Ska förtydliga mig. I vår kommun kräver de inte personnummer, endast födelsedatum. Det är inte det som är mitt förslag. Det är helt ok att personnumret lagras i Skojjt (t o m nödvändigt för vissa användare, och är med i exporten).

Det är vid det dagliga användandet av Skojjt, som personnumret blir "överflödigt", och skapar en känsla av "obekvämlighet" då man plötsligt måste se upp med vem som har tillgång till informationen. Det gäller ju alltid förvisso, men. Det skulle underlätta väsentligen i verksamheten om man lättare kunde ge fler tillgång till Skojjt och ansvara för närvaron. Då med vetskapen om att de inte har tillgång till känslig personlig information, utan endast det som är nödvändigt för verksamheten.

Jag upplever att namn, mobil, e-post till medlem samt namn mobil, e-post för anhörig 1 och 2 är de uppgifter som jag har mest behov av i verksamheten. Oftast för att enkelt kolla om man är försenad/sjuk, eller för att snabbt kunna meddela anhörig om något har hänt. Och att då kunna använda Skojjt som ett verktyg för att ge ansvariga, funktionärer och andra som måste ta ansvar för scouterna möjlighet att på ett enkelt sätt få tillgång till nödvändiga kontaktuppgifter, är en stor fördel, och kan på ett enkelt sätt få bort diverse hemmagjorda utskrivna listor, öka säkerheten och göra det enklare för en scoutkår att följa GDPR.

Så personnumret (men även gatuadress, mm) kan kanske vara synligt i Skojjt för kåradmin och i exporten. Men inte för vanliga användare. Där är det isåfall viktigare med avdelning och patrull.

**Comment by puggan** [comment]
Tack för förtydligandet, överlåter till Martin att besluta vad som ska göras.

**Comment by martin-green** [comment]
- [ ] Jag kan gömma fyra sista siffrorna för icke admin

Det är bra att kunna se födelsedatum för alla ledare. Göteborgs kommun har backat från kravet på personnummer, men jag vet inte hur det är i andra kommuner.
Jag använder personnummer som ett id nummer när man lägger till en person från skojjt till scoutnet (kölistan). Det var det enda sättet som jag kom på att matcha personen när den kommer tillbaka från scoutnet vid nästa import. Om Kö API:t hade returnerat id-numret i scoutnet så hade jag inte behövt det.

- [ ] Jag försöker gå igenom den API ändringen hos scoutnet

**Comment by rkalitta** [comment]
👍
