### ISSUE TITLE
Excel rapport för kommuner utan digital rapportering

### ISSUE THREAD

**Issue by martin-green** [martin-green/skojjt#72]
Exporten ska vara samma data som för dak eller sensus.
Exempelmall från Stockholm:
http://www.stockholm.se/PageFiles/95405/F%c3%b6reningsblanketter%202014/2019/N%c3%a4rvarokortt%20exempel%202019.xls

**Comment by martin-green** [comment]
Finns på avdelningens sida, under knappen "Närvarorapport"/"Excelrapport".

**Comment by rkalitta** [comment]
Det här är Kung! Jag vill inte bråka, ser att ärendet är stängt. Men har en fundering. Tyvärr så verkar kommuner ha olika uppfattning om hur åldersindelningen ska vara på deltagartillfällen. Vad är en bra lösning på det? Ska man kunna ange i Skojjt hur man vill ha indelningen i xlsx-filen? (Överambitiöst!) 

Så här måste vi rapportera.
[https://etjanster.ostersund.se/FileStorageArea/Blanketter/32/ansokanlokstod.pdf](url)

En idé är att skapa de kolumnerna i Excel (som i Stockholmsmallen AJ - AQ) med en formel så att man får själv justera efter behov, genom att ändra textrubriken i AJ13 - AQ13. I Google sheet (vet inte hur i Excel), som exempel, skulle översta raden (15), cell AN15 bli:
=OMFEL(OM(OCH(DATEDIF("2018-01-01";J15;"Y") >= VALUE(REGEXEXTRACT(AN$13;"^[0-9]*"));DATEDIF("2018-01-01";J15;"Y") <= VALUE(REGEXEXTRACT(AN$13;"[0-9]*$"));$...KÖN...="K"); SUM($K15:$AI15);"");"")

Periodbeskrivningen har jag gjort till egna celler med fullt datum. T ex i exporten är D6 = 2019-01-01. E6 = "-". F6 = 201-06-30. I formeln ovan har skrivit in datumet istället för referens till cellen. Kön ovan i formeln motsvarar H13 i exporten.

Detta gör det möjligt för alla kårer att själva justera åldrarna i kolumnerna efter behov. Och jag tror att de flesta kommunerna behöver tre kolumner för respektive pojkar och flickor, samt två för ledare, åtta kolumner totalt.

Dessutom en kolumn som summerar antal sammankomster.

Hoppas du förstod min beskrivning. Är detta en möjlig lösning?

**Comment by puggan** [comment]
Formler på svenska är ju hemskt, ush,
Hittade dock ett verktyg för att byta språk:
https://en.excel-translator.de/translator/

Testade att konvertera den till Engelska
`=IFERROR(IF(AND(DATEDIF("2018-01-01",J15,"Y") >= VALUE(REGEXEXTRACT(AN$13,"^[0-9]")),DATEDIF("2018-01-01",J15,"Y") <= VALUE(REGEXEXTRACT(AN$13,"[0-9]$")),$...KÖN...="K"), SUM($K15:$AI15),""),"")`

Indenterade den för att försöka förstå den:
```
=
	IFERROR(
		IF(
			AND(
					// Years from J15 to begining of 2018
					DATEDIF("2018-01-01",J15,"Y")
				// Greater then numeric value in AN13
				>=
					VALUE(
						REGEXEXTRACT(
							AN$13,
							"^[0-9]"
						)
					),
				// AND

					// Years from J15 to begining of 2018
					DATEDIF("2018-01-01",J15,"Y")
				// Less then numeric value in AN13
				<=
					VALUE(
						REGEXEXTRACT(
							AN$13,
							"[0-9]$"
						)
					),
				// AND
				// ???
				$...KÖN...="K"
			), 
			// Then
			SUM($K15:$AI15),
			// Else
			""),
		// On error
		""
	)
```

Vad är `$...KÖN...="K"`?
Förstod inte den delen, och hittade inget bra att google på..

**Comment by rkalitta** [comment]
Kön ovan i formeln motsvarar H13 i exporten.
