### ISSUE TITLE
Acceptera kön == Annat

### ISSUE THREAD

**Issue by tobbee** [martin-green/skojjt#76]
Vi har några medlemmar som inte vill vara registerade som man eller kvinna utan kön==Annat.
I dagsläget vägrar Skojjt importera dessa vilket är olyckligt. Jag tänkte därförlägga lite kod på det.

Min idé är att spara Scoutnets

kön = 0 (annat), 1 (man) och 2

som en integer

men behålla person.female som boolean för att fylla i rapporter. 

person.female tas antingen tas direkt från köns-fältet, eller från personnumrets näst sista siffra om kön==Annat.

Kommentarer om detta?

**Comment by puggan** [comment]
Summering:
* Exporterna/Rapporterna kräver binärt kön
* Scoutnet har 3 kön.
* Skojjt preseterar inte kön någonstans(?) men behöver det eller personnummeret för att kunna exportera.

Ser ingen vinst med att koda in 3 alterntiv i skojjt, om det inte presenteras någonstans i skojjt.
(Ser heller inga problem med att spara de 3 som finns i scoutnet.)

**Comment by martin-green** [comment]
Det var så att scoutnet hade icke personer registrerade i registret. Det var förmodligen en rest från Melker konverteringen, så många hade sin scoutkår som en post i medlemsregistret. Jag ville inte släppa igenom sånt till skojjt, för det skulle ge problem vid rapporteringen. Men nu kollar vi att det är ett rimligt personnummer istället så jag kan ta bort kön kollen helt.
