### ISSUE TITLE
Avdelningar dyker inte upp

### ISSUE THREAD

**Issue by tobbee** [martin-green/skojjt#77]
Har precis satt upp en egen instans av skojjt för våra ledare som alla har google-adresser via G-Suite för Non-profit organizations. Det verkar som att de kan lägga till sig själva eftersom det är samma domän som jag registrerat i Google App Engine, men de andra ledarna ser inga avdelningar i listan under termin 2019-vt. De kan dock se alla medlemmar. Jag har också gjort en testanvändare som kan se listan på avdelningar.

Är det någon som vet vad detta beror på och hur jag kan fixa detta?

**Comment by martin-green** [comment]
Prova på Admin sidan, "Byt till ny termin för alla användare".

Den 2019-02-12 kl. 17:45, skrev Torbjörn Einarson:

**Comment by martin-green** [comment]
Ska vara fixat för nya användare nu.

**Comment by tobbee** [comment]
Tackar. Jag misstänkte att det var terminen som var "osatt", men visste inte riktigt varför.
