### ISSUE TITLE
Importfel: no matching index found

### ISSUE THREAD

**Issue by hakankvist** [martin-green/skojjt#86]
Hej!

Vi har installerat skojjt på en separat installation i vår scoutkår. Första gång vi kör importen från scoutnet enligt instruktionerna på sidan https://github.com/martin-green/skojjt/wiki/Hur-man-importerar-medlemmar-fr%C3%A5n-scoutnet (metod 1), så imporeteras en hel del medlemmar, men längst ner på resultatsidan så får vi ett felmeddelande som säger:

Importfel: no matching index found. recommended index is: - kind: Person properties: - name: scoutgroup - name: removed The suggested index for this query is: - kind: Person properties: - name: scoutgroup - name: removed

Vad är detta för typ av fel, är det fel i datan i scoutnet?
Går det i så fall säga vilken användare som orsakade detta problemet, är det den sista personen som importerats enligt loggen eller är det det nästkommande person?

**Comment by hakankvist** [comment]
Vet inte om det spelar roll eller om det är nollindexering som spökar.

När jag gör importen så kommer först en utskrift som säger:
Importerar för termin 2019-ht
--
antal personer=137


Men vi har 138 medlemmar.
Tittar man statusrapporten på raderna innan felmeddelandet, så skriver den ut "ny medlem" 138 gånger, så den verkar ha hittat 138 namn.

**Comment by kesse** [comment]
Hej, 

Felet ni får är att det saknas index i databasen.
Har ni kört "gcloud app deploy index.yaml --project skojjt-X" ?

**Comment by hakankvist** [comment]
Hejsan, mycket riktigt, det hade vi missat.
Nu väntar vi på att initieringen av databasen ska bli färdig, så kommer vi försöka igen senare när den är färdig.

Tack för den snabba hjälpen.

**Comment by kesse** [comment]
Varsågod, hoppas allt går bra för er med skojjt.
