### ISSUE TITLE
Lägerbidragsansökan (åtminstone Stockholm) via Skojjt

### ISSUE THREAD

**Issue by tobbee** [martin-green/skojjt#88]
Tänkte försöka få till ifyllnad av lägerbidragsansökan till Stockholms Idrottsförvaltning via Skojjt. Tanken är att man avdelningsvis skall kunna fylla i en blankett för lägerbidragsansökan genom att kryssa för de scouter som var med, fylla i lite uppgifter om plats, datum etc och sen trycka på en knapp varvid ett ifyllt Word-dokument skapas.

Har börjat genom att stoppa in en massa MERGEFIELD i deras mall, så att jag programmatiskt kan fylla i alla fält via `docx-mailmerge`-module.  Ser ut att funka bra. Om någon gör/gjort något liknande, vill hjälpa till eller göra något för någon annan del av landet, är det förstås bra om vi kan hjälpas åt. Tänkte öppna en Pull Request som 'Work in Progress'  när jag kommit lite längre.

**Comment by tobbee** [comment]
Hittade en PR för lägerbidrag i Gbg https://github.com/martin-green/skojjt/pull/84  så jag tittar på den koden innan jag går vidare.

**Comment by kesse** [comment]
Låter lite som funktionen som jag byggde för att söka lägerbidrag för göteborgs kommun. 
Där väljer man datum och så tar den ut alla som varit på minst 3 dagar, är krav på minst 2 nätter för att får lägerbidrag i göteborg.

Borde går att bygga ut den funktionen med olika rapporter och regler för uträkning efter kommun.

**Comment by tobbee** [comment]
Japp. Tack för responsen @kesse. Har kollat lite på funktionen nu. I Stockholm är det minst 1, max 6 nätter och ålder 7-20år, så man skulle behöva ändra gränserna. Man skall dock inte ha med de dagar man har läger i närvarorapporten, så det känns som att det vore bättre att skilja dem åt, så att närvaro på läger har en speciell rapportering. Har du några funderingar på det?

**Comment by tobbee** [comment]
Har funderat en vända till. Kanske kan utöka möte med en flagga som talar om det är en del av ett läger. Då skulle man kunna använda denna flagga till att
1) se till att en närvarorapport över möten inte tar med lägerdagar.
2) att start-tid och längd inte är relevant
Alternativt skulle man kunna ge ett slutdatum som indikation på att mötet är "flerdagars" och därmed vara ett läger istället...

**Comment by puggan** [comment]
Lägg till möte, kanske kunde utökas med en lägg till läger,
där man väljer startdag och slutdag, och så skapar den ett möte för vardera (så det blir kompatibelt med de rapporter som behöver en per dag), men att de har en flagga som tex pekar på första dagen. Men kanske borde ligga som en egen issue/feturerequest.

**Comment by tobbee** [comment]
Jag har gjort följande hittills:
* satt in en checkbox under möte där man kan säga "del av läger". Den kan "togglas" av och på.
* kryssar man i så ändras färgen på mötet från blått till grönt och starttid och längd göms
* Dett val lagras som en extra parameter (ishike) i Meeting.
* Gjort en ny knapp för Lägerbidrag Stockholm och ett formulär med lite fler uppgifter som man behöver i Stockholm

Eftersom det är ifyllnad dag för dag vore det kanske bra med en extra knapp där man kan kopiera närvaron från föregående dag. Det får bli i en senare version.

Återstår att fixa till filtrering med andra regler och genera en annan rapport (skall ha postadress).
Blir en PR relativt snart.

**Comment by tobbee** [comment]
PR #89 täcker detta, så jag stänger denna issue.
