### ISSUE TITLE
Efternamnet klips av

### ISSUE THREAD

**Issue by puggan** [martin-green/skojjt#9]
Om en person har dubbla efternamn, så klipper den av dem mitt i andra efternamnet, efter 10 bokstäver.

Varför en maxlängd på 10?

och vad ska pattern delen göra? om den ska bara visa första efternamnet så funkar den inte, ska antagligen vara `re.compile("[\( -]")`

```
		pattern = re.compile("\( -")
		fn = self.firstname #pattern.split(self.firstname)[0][:10]
		ln = pattern.split(self.lastname)[0][:10]
```

**Comment by martin-green** [comment]
Jag vill hålla ner längden på namn, det ska funka i mobilen också.


Den 2016-11-09 kl. 13:56, skrev puggan:

**Comment by puggan** [comment]
ah, då vet jag varför.

ska testa lösa det med css istället,
typ `width: ??px` i combination med `overflow: hidden`

**Comment by puggan** [comment]
Inte lika relevant efter att namnets längf inte längre är begränsat: 0a54c59777a6fc12d55665ccdab357bc5905ded1

Men ska försöka få tid över att titta på det senare.
