### ISSUE TITLE
Del av läger, vid edit

### ISSUE THREAD

**Issue by puggan** [martin-green/skojjt#92]
Om man har ett tidigare ifyllt möte/lägerdag, och kryssar i "Del av läger",
så skrivs vissa fält över.

Den funktionaliteten borde inte finnas på edit,
och då det finns en "Lägg till läger" så behövs den antagligen inte heller på "Lägg till möte".

![Screenshot from 2019-09-01 08-58-06](https://user-images.githubusercontent.com/866668/64072889-b7a95780-cc96-11e9-8ba8-3bcef49c6462.png)
![Screenshot from 2019-09-01 08-58-16](https://user-images.githubusercontent.com/866668/64072888-b7a95780-cc96-11e9-901d-7e337abaf1e7.png)

**Comment by tobbee** [comment]
Kan förstå att detta är ett problem om man vill lägga till läger-status i efterhand. För nya registreringar borde det inte vara något problem. Min tanke med att att det ändras när man togglar är att man skulle förstå att läger är flerdagsaktivitet, medan möte inte är det.

Borde vi sikta på att det ändras bara om det som står inte är "default-värdena"?

Dvs, står det "Möte" Starttid 18:00 Längd 80 (eller vad nu default-tiden är), så ändras det till "Läger, 00, 1440", och tvärtom, men om står det något annat så ändras det inte.

**Comment by puggan** [comment]
Antingen något åt det hållet, eller ta bort toggle-funktionaliteten helt nu när "Lägg till läger"-knappen finns.

PS, start-tiden kommer från inställningarna på avdelningen:
![Screenshot from 2019-09-10 09-40-04](https://user-images.githubusercontent.com/866668/64593772-ecac5d00-d3ae-11e9-8c4c-fd33578ad08f.png)

**Comment by tobbee** [comment]
Borde kunna stänga denna nu efter att PR #93 mergats.
